name: Build and Push Container Image

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{github.repository}}

on:
    push:
        branches: [ "main"]

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write

        steps:
        - name: Checkout Setup QEMU
          uses: docker/setup-qemu-action@v3.2.0

        - name: Setup Docker Buildx
          uses: docker/setup-buildx-action@v3.7.1
          with:
            platforms: linux/amd64,linux/arm64

        - name: Log into Registry
          uses: docker/login-action@v3.3.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Build and push
          uses: docker/build-push-action@v6.9.0
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: |
                ghcr.io/ckriutz/simplewebapp:latest
                ghcr.io/ckriutz/simplewebapp:${{github.run_number}}
